apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mrms-backend.fullname" . }}-secret
  labels:
    {{- include "mrms-backend.labels" . | nindent 4 }}
type: Opaque
{{- if .Values.secrets.immutable.enabled }}
immutable: true
{{- end }}
stringData:
  {{- toYaml .Values.secret | nindent 2 }}
