const sql = `
select
    m_.model_name,
    m_.model_desc,
    m_.model_version,
    'sum-rm' as model_source,
    (case when m_.root_model_id != '' then
        (cast('model' || m_.root_model_id as varchar(4000)) || '-v' ||
            cast(m_.model_version as varchar(4000)))
    else null end) as model_alias,
    m_.update_date,
    a.*
from models_new m_
inner join (
    select
        model_id as system_model_id,
        max(case when artefact_id = 2000 then artefact_string_value else null end) as record_id,
        max(case when artefact_id = 2001 then artefact_string_value else null end) as model_id,
        max(case when artefact_id = 2002 then artefact_string_value else null end) as group_company,
        max(case when artefact_id = 2003 then artefact_string_value else null end) as rating_system_name,
        max(case when artefact_id = 2004 then artefact_string_value else null end) as regulatory_code_rs_pvr,
        max(case when artefact_id = 2005 then artefact_string_value else null end) as description_rating_system,
        max(case when artefact_id = 2006 then artefact_string_value else null end) as model_crs_code,
        max(case when artefact_id = 2007 then artefact_string_value else null end) as model_type,
        max(case when artefact_id = 2008 then artefact_string_value else null end) as identifier_model_algorithm_for_rwa,
        max(case when artefact_id = 2009 then artefact_string_value else null end) as regulatory_code_model_pvr,
        max(case when artefact_id = 2010 then artefact_string_value else null end) as internal_model_number,
        max(case when artefact_id = 2011 then artefact_string_value else null end) as active_model,
        max(case when artefact_id = 2012 then artefact_string_value else null end) as model_indicator,
        max(case when artefact_id = 2013 then artefact_string_value else null end) as calibration_version,
        max(case when artefact_id = 2014 then artefact_string_value else null end) as calibration_version,
        max(case when artefact_id = 2015 then artefact_string_value else null end) as calibration_date,
        max(case when artefact_id = 2016 then artefact_string_value else null end) as regulatory_code_of_asset_class,
        max(case when artefact_id = 2017 then artefact_string_value else null end) as model_id_from_model_owner,
        max(case when artefact_id = 2018 then artefact_string_value else null end) as classification_rs_algorithm_by_asset_classes,
        max(case when artefact_id = 2019 then artefact_string_value else null end) as significance_validity,
        max(case when artefact_id = 2020 then artefact_string_value else null end) as degree_of_regulatory_supervision,
        max(case when artefact_id = 2021 then artefact_string_value else null end) as materiality_rate,
        max(case when artefact_id = 2022 then artefact_string_value else null end) as impact_coverage,
        max(case when artefact_id = 2023 then artefact_string_value else null end) as responsible_for_significance_validity,
        max(case when artefact_id = 2024 then artefact_string_value else null end) as classification_of_rs_by_order_of_application_within_pvr,
        max(case when artefact_id = 2025 then artefact_string_value else null end) as credit_risk_component,
        max(case when artefact_id = 2026 then artefact_string_value else null end) as method_calculation_model_parameter,
        max(case when artefact_id = 2027 then artefact_string_value else null end) as segment_name,
        max(case when artefact_id = 2028 then artefact_string_value else null end) as implementation_segment,
        max(case when artefact_id = 2029 then artefact_string_value else null end) as regulatory_class,
        max(case when artefact_id = 2030 then artefact_string_value else null end) as regulatory_subclass,
        max(case when artefact_id = 2031 then artefact_string_value else null end) as business_customer,
        max(case when artefact_id = 2032 then artefact_string_value else null end) as business_customer_departament,
        max(case when artefact_id = 2033 then artefact_string_value else null end) as goals_using_results_of_work_rs,
        max(case when artefact_id = 2034 then artefact_string_value else null end) as implementation_validity,
        max(case when artefact_id = 2035 then artefact_string_value else null end) as validity_approve,
        max(case when artefact_id = 2036 then artefact_string_value else null end) as bank_document,
        max(case when artefact_id = 2037 then artefact_string_value else null end) as remove_date,
        max(case when artefact_id = 2038 then artefact_string_value else null end) as remove_decision,
        max(case when artefact_id = 2039 then artefact_string_value else null end) as ds_department,
        max(case when artefact_id = 2040 then artefact_string_value else null end) as developing_start_date,
        max(case when artefact_id = 2041 then artefact_string_value else null end) as developing_end_date,
        max(case when artefact_id = 2042 then artefact_string_value else null end) as data_source_description,
        max(case when artefact_id = 2043 then artefact_string_value else null end) as target,
        max(case when artefact_id = 2044 then artefact_string_value else null end) as calibration_method,
        max(case when artefact_id = 2045 then artefact_string_value else null end) as analize_text_about_developing,
        max(case when artefact_id = 2046 then artefact_string_value else null end) as name_and_version_rating_system,
        max(case when artefact_id = 2047 then artefact_string_value else null end) as version_it_implementation,
        max(case when artefact_id = 2048 then artefact_string_value else null end) as responsible_subdivision_and_project_lead_for_it_implementation,
        max(case when artefact_id = 2049 then artefact_string_value else null end) as date_of_it_introduction_into_operation,
        max(case when artefact_id = 2050 then artefact_string_value else null end) as psi_protocol,
        max(case when artefact_id = 2051 then artefact_string_value else null end) as validation_department,
        max(case when artefact_id = 2052 then artefact_string_value else null end) as plan_validation_type,
        max(case when artefact_id = 2053 then artefact_string_value else null end) as validation_period,
        max(case when artefact_id = 2054 then artefact_string_value else null end) as validation_report_approve_date,
        max(case when artefact_id = 2055 then artefact_string_value else null end) as validation_result_approve_date,
        max(case when artefact_id = 2056 then artefact_string_value else null end) as auto_validation_result,
        max(case when artefact_id = 2057 then artefact_string_value else null end) as importance_changes,
        max(case when artefact_id = 2058 then artefact_string_value else null end) as approve_importance,
        max(case when artefact_id = 2059 then artefact_string_value else null end) as approve_importance_changes,
        max(case when artefact_id = 2060 then artefact_string_value else null end) as date_and_number_regulator_notification,
        max(case when artefact_id = 2061 then artefact_string_value else null end) as date_submission_to_regulator,
        max(case when artefact_id = 2062 then artefact_string_value else null end) as start_date_of_application_model_approved_regulator,
        max(case when artefact_id = 2063 then artefact_string_value else null end) as decision_date_of_application_model_for_segment,
        max(case when artefact_id = 2064 then artefact_string_value else null end) as decision_number_of_application_model_for_segment,
        max(case when artefact_id = 2065 then artefact_string_value else null end) as notification_date_of_application_model_for_segment,
        max(case when artefact_id = 2066 then artefact_string_value else null end) as notification_number_of_application_model_for_segment,
        max(case when artefact_id = 2067 then artefact_string_value else null end) as decision_date_of_application_model,
        max(case when artefact_id = 2068 then artefact_string_value else null end) as decision_number_of_application_model,
        max(case when artefact_id = 2069 then artefact_string_value else null end) as notification_date_of_application_model,
        max(case when artefact_id = 2070 then artefact_string_value else null end) as notification_number_of_application_model,
        max(case when artefact_id = 2071 then artefact_string_value else null end) as model_risk_type,
        max(case when artefact_id = 2072 then artefact_string_value else null end) as model_changes_info,
        max(case when artefact_id = 2073 then artefact_string_value else null end) as rfd,
        max(case when artefact_id = 2074 then artefact_string_value else null end) as ds_stream,
        max(case when artefact_id = 2075 then artefact_string_value else null end) as assignment_contractor,
        max(case when artefact_id = 2076 then artefact_string_value else null end) as model_epic_04,
        max(case when artefact_id = 2077 then artefact_string_value else null end) as model_epic_04_date,
        max(case when artefact_id = 2078 then artefact_string_value else null end) as model_epic_05,
        max(case when artefact_id = 2079 then artefact_string_value else null end) as model_epic_05a,
        max(case when artefact_id = 2080 then artefact_string_value else null end) as data_completion_of_stage_05a,
        max(case when artefact_id = 2081 then artefact_string_value else null end) as solution_to_implement_model,
        max(case when artefact_id = 2082 then artefact_string_value else null end) as model_epic_07,
        max(case when artefact_id = 2083 then artefact_string_value else null end) as model_epic_07_date,
        max(case when artefact_id = 2084 then artefact_string_value else null end) as custom_model_id,
        max(case when artefact_id = 2085 then artefact_string_value else null end) as custom_model_type,
        max(case when artefact_id = 2086 then artefact_string_value else null end) as release,
        max(case when artefact_id = 2087 then artefact_string_value else null end) as model_epic_09,
        max(case when artefact_id = 2088 then artefact_string_value else null end) as model_epic_11,
        max(case when artefact_id = 2089 then artefact_string_value else null end) as model_epic_11_date,
        max(case when artefact_id = 2090 then artefact_string_value else null end) as model_epic_12,
        max(case when artefact_id = 2091 then artefact_string_value else null end) as model_epic_12_date,
        max(case when artefact_id = 2092 then artefact_string_value else null end) as pvr,
        max(case when artefact_id = 2093 then artefact_string_value else null end) as model_version,
        max(case when artefact_id = 2094 then artefact_string_value else null end) as validity_approve_date,
        max(case when artefact_id = 2095 then artefact_string_value else null end) as validation_result,
        max(case when artefact_id = 2096 then artefact_string_value else null end) as model_name_dadm,
        max(case when artefact_id = 2097 then artefact_string_value else null end) as decision_date_and_number_of_application_model_for_segment,
        max(case when artefact_id = 2098 then artefact_string_value else null end) as notification_date_and_number_of_application_model_for_segment,
        max(case when artefact_id = 2099 then artefact_string_value else null end) as decision_date_and_number_of_application_model,
        max(case when artefact_id = 2100 then artefact_string_value else null end) as notification_date_and_number_of_application_model,
        max(case when artefact_id = 2101 then artefact_string_value else null end) as model_status,
        max(case when artefact_id = 2102 then artefact_string_value else null end) as model_status_assignee,
        max(case when artefact_id = 2104 then artefact_string_value else null end) as developing_model_reason,
        max(case when artefact_id = 2105 then artefact_string_value else null end) as product_name,
        max(case when artefact_id = 2106 then artefact_string_value else null end) as provides_piloting,
        max(case when artefact_id = 2107 then artefact_string_value else null end) as operational_monitoring,
        max(case when artefact_id = 2108 then artefact_string_value else null end) as analytical_monitoring
    from artefact_realizations_new arn
    group by model_id
) a on m_.model_id = a.system_model_id;
`;

export { sql };
