import { LIFE_CYCLE_STAGES } from 'src/system/common/constants'

export const VALID_BPMN_KEYS = [
  LIFE_CYCLE_STAGES.MAIN,
  LIFE_CYCLE_STAGES.INITIALIZATION,
  LIFE_CYCLE_STAGES.DATA,
  LIFE_CYCLE_STAGES.DATA_SEARCH,
  LIFE_CYCLE_STAGES.DATA_PILOT,
  LIFE_CYCLE_STAGES.DATA_BUILD,
  LIFE_CYCLE_STAGES.MODEL,
  LIFE_CYCLE_STAGES.MODEL_VALIDATION,
  LIFE_CYCLE_STAGES.INTEGRATION,
  LIFE_CYCLE_STAGES.INTEGRATION_DATAMART,
  LIFE_CYCLE_STAGES.INTEGRATION_ENV_CONF,
  LIFE_CYCLE_STAGES.INTEGRATION_TEST,
  LIFE_CYCLE_STAGES.INTEGRATION_USER,
  LIFE_CYCLE_STAGES.INTEGRATION_PROD,
  LIFE_CYCLE_STAGES.CANCEL
]

