--liquibase formatted sql

--changeset d.kravchenko:26_12_23_03_add_purs_default_template
--comment: Добавление шаблона "Реестр рейтинговых систем в соответствии с ПУРС"

INSERT INTO templates (group_id, template_label, template_value)
VALUES (1, 'Реестр рейтинговых систем в соответствии с ПУРС', '{
  "record_id": [
    "not-null"
  ],
  "group_company": [],
  "update_date": [],
  "rating_system_name": [],
  "regulatory_code_rs_pvr": [],
  "description_rating_system": [],
  "model_name": [],
  "model_desc": [],
  "model_type": [],
  "identifier_model_algorithm_for_rwa": [],
  "regulatory_code_model_pvr": [],
  "model_version": [],
  "internal_model_number": [],
  "active_model": [],
  "model_indicator": [],
  "calibration_version": [],
  "calibration_date": [],
  "regulatory_code_of_asset_class": [],
  "model_id_from_model_owner": [],
  "classification_rs_algorithm_by_asset_classes": [],
  "significance_validity": [],
  "degree_of_regulatory_supervision": [],
  "materiality_rate": [],
  "impact_coverage": [],
  "responsible_for_significance_validity": [],
  "classification_of_rs_by_order_of_application_within_pvr": [],
  "credit_risk_component": [],
  "method_calculation_model_parameter": [],
  "segment_name": [],
  "implementation_segment": [],
  "regulatory_class": [],
  "regulatory_subclass": [],
  "business_customer": [],
  "business_customer_department": [],
  "goals_using_results_of_work_rs": [],
  "implementation_validity": [],
  "validity_approve": [],
  "validity_approve_date": [],
  "bank_document": [],
  "remove_date": [],
  "ds_department": [],
  "developing_start_date": [],
  "developing_end_date": [],
  "data_source_description": [],
  "target": [],
  "calibration_method": [],
  "analize_text_about_developing": [],
  "name_and_version_rating_system": [],
  "version_it_implementation": [],
  "responsible_subdivision_and_project_lead_for_it_implementation": [],
  "date_of_it_introduction_into_operation": [],
  "psi_protocol": [],
  "validation_department": [],
  "plan_validation_type": [],
  "validation_period": [],
  "validation_report_approve_date": [],
  "validation_result": [],
  "validation_result_approve_date": [],
  "auto_validation_result": [],
  "importance_changes": [],
  "approve_importance": [],
  "approve_importance_changes": [],
  "date_and_number_regulator_notification": [],
  "date_submission_to_regulator": [],
  "decision_date_of_application_model": [],
  "decision_number_of_application_model": [],
  "notification_date_of_application_model": [],
  "notification_number_of_application_model": [],
  "decision_date_of_application_model_for_segment": [],
  "decision_number_of_application_model_for_segment": [],
  "notification_date_of_application_model_for_segment": [],
  "notification_number_of_application_model_for_segment": [],
  "start_date_of_application_model_approved_regulator": []
}');
