export const AUDIT_EVENT_SUMD_AUTH = 'SUMD_AUTH';
export const AUDIT_EVENT_SUMD_MRMSCREATEMODEL = 'SUMD_MRMSCREATEMODEL';
export const AUDIT_EVENT_SUMD_MRMSREMOVEMODEL = 'SUMD_MRMSREMOVEMODEL';
export const AUDIT_EVENT_SUMD_MRMSUPLOADREPORT = 'SUMD_MRMSUPLOADREPORT';
export const AUDIT_EVENT_SUMD_MRMSEDITMODEL = 'SUMD_MRMSEDITMODEL';

export const DEFAULT_SIDECAR_URL = 'http://localhost:8081/api/v2/audit';
export const DEFAULT_TIMEOUT_MS = 3000;
export const DEFAULT_RETRY_INTERVAL_MS = 30000;
export const DEFAULT_GENERATOR_INTERVAL_MS = 10000;