export enum LIFE_CYCLE_STAGES {
  MAIN = 'main',
  INITIALIZATION = 'initialization',
  MODEL = 'model',
  DATA = 'data',
  DATA_BUILD = 'data_build',
  DATA_SEARCH = 'data_search',
  DATA_PILOT = 'data_pilot',
  INTEGRATION = 'integration',
  INTEGRATION_DATAMART = 'integration_datamart',
  INTEGRATION_ENV_CONF = 'integration_env_conf',
  INTEGRATION_TEST = 'integration_test',
  INTEGRATION_USER = 'integration_user',
  INTEGRATION_PROD = 'integration_prod',
  MODEL_VALIDATION = 'model_validation',
  MONITORING = 'monitoring',
  VALIDATION = 'validation',
  MONITORING_AUTO_CORRECT = 'monitoring_auto_correct',
  REMOVAL = 'removal',
  JIRA = 'jira',
  DEVELOPED_NOT_IMPLEMENTED = 'developed_not_implemented',
  ROLLBACK_VERSION = 'rollback_version',
  ROLLBACK = 'rollback',
  FAST_MODEL_PROCESS = 'fast_model_process',
  MODEL_PILOT = 'model_pilot',
  FULLVALIDATION_DATAMART = 'fullvalidation_datamart',
  INTEGRATION_MODEL = 'inegration_model',
  TEST_PREPROD_TRANSFER_PROD = 'test_preprod_transfer_prod',
  FULLVALIDATION = 'fullvalidation',
  CANCEL = 'cancel',
  MODEL_STATE_TRANSITION = 'model_state_transition'
}

export const LIFE_CYCLE_STAGES_DESCRIPTION: Record<LIFE_CYCLE_STAGES, string> =
  {
    [LIFE_CYCLE_STAGES.MAIN]: 'Процесс родитель',
    [LIFE_CYCLE_STAGES.INITIALIZATION]: 'Инициализация',
    [LIFE_CYCLE_STAGES.MODEL]: 'Разработка модели',
    [LIFE_CYCLE_STAGES.DATA]: 'Данные',
    [LIFE_CYCLE_STAGES.DATA_BUILD]: 'Разработка витрины',
    [LIFE_CYCLE_STAGES.DATA_SEARCH]: 'Поиск данных',
    [LIFE_CYCLE_STAGES.DATA_PILOT]: 'Пилот данных',
    [LIFE_CYCLE_STAGES.INTEGRATION]: 'Внедрение',
    [LIFE_CYCLE_STAGES.INTEGRATION_DATAMART]: 'Разработка промышленной витрины',
    [LIFE_CYCLE_STAGES.INTEGRATION_ENV_CONF]: 'Настройка среды применения',
    [LIFE_CYCLE_STAGES.INTEGRATION_TEST]: 'Тестирование ДИТ',
    [LIFE_CYCLE_STAGES.INTEGRATION_USER]: 'Пользовательское тестирование',
    [LIFE_CYCLE_STAGES.INTEGRATION_PROD]: 'Перенос на промышленный стенд',
    [LIFE_CYCLE_STAGES.MODEL_VALIDATION]: 'Первичная валидация',
    [LIFE_CYCLE_STAGES.MONITORING]: 'Мониторинг',
    [LIFE_CYCLE_STAGES.VALIDATION]: 'Внедрена',
    [LIFE_CYCLE_STAGES.MONITORING_AUTO_CORRECT]:
      'Автоматизированная корректировка',
    [LIFE_CYCLE_STAGES.REMOVAL]: 'Вывод модели из эксплуатации',
    [LIFE_CYCLE_STAGES.JIRA]: 'Создание задачи Jira',
    [LIFE_CYCLE_STAGES.DEVELOPED_NOT_IMPLEMENTED]: 'Разработана, не внедрена',
    [LIFE_CYCLE_STAGES.ROLLBACK_VERSION]: '',
    [LIFE_CYCLE_STAGES.ROLLBACK]: 'Откат',
    [LIFE_CYCLE_STAGES.FAST_MODEL_PROCESS]:
      'Сокращенное заведение разработанных моделей',
    [LIFE_CYCLE_STAGES.MODEL_PILOT]: 'Пилотирование модели',
    [LIFE_CYCLE_STAGES.FULLVALIDATION_DATAMART]:
      'Разработка витрины для полной валидации',
    [LIFE_CYCLE_STAGES.INTEGRATION_MODEL]: 'Продуктивизация модели',
    [LIFE_CYCLE_STAGES.TEST_PREPROD_TRANSFER_PROD]:
      'Тестирование на препрод и перенос на прод контур',
    [LIFE_CYCLE_STAGES.FULLVALIDATION]: 'Полная валидация',
    [LIFE_CYCLE_STAGES.CANCEL]: 'Отмена разработки модели',
    [LIFE_CYCLE_STAGES.MODEL_STATE_TRANSITION]: 'Транзит состояния модели'
  }
